server:
  port: 8091
  
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: true
  application:
    zipkin: http://localhost:9411

