server:
  port: 8091
  servlet:
    context-path: /books
    session:
      timeout: 21600s
spring:
  application:
    name: book-service
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

