server:
  port: 8093
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: true
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
feign:
  hystrix:
    enabled: true
    dashboard:
      proxyStreamAllowList: '*'
  circuitbreaker:
    enabled: true
  ribbon:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
book-service:
  ribbon:
    listOfServers: localhost:9095
rating-service:
  ribbon:
    listOfServers: localhost:9999