server:
  port: ${PORT:${SERVER_PORT:0}}

eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: true
  application:
    zipkin: http://localhost:9411

feign:
  hystrix:
    enabled: true
    dashboard:
      proxyStreamAllowList: '*'
  circuitbreaker:
    enabled: true
  ribbon:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

ping-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8091, localhost:8092
    ServerListRefreshInterval: 15000