server:
  port: 8092
  servlet:
    context-path: /ratings
    session:
      timeout: 21600s
spring:
  application:
    name: rating-service
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost