server:
  port: ${PORT:${SERVER_PORT:0}}
  
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: true
  application:
    zipkin: http://localhost:9411